// nao-dev/api/v1/applications/applicationId/KycCheck?type=tin_verification

export const CurrentkYCResponseStructure = {
  data: [
    {
      naoUserId: "5tH5YUUSNqpPqrAzXci1",
      checks: {
        politically_exposed_person_report: [
          {
            id: "e31b832a-ed48-48e0-9af4-3831070659fb",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_jcJiiSPV4xxeyPzdaaeLKM1Ag7tk",
            displayName: "POLITICALLY_EXPOSED_PERSON_REPORT",
            description: "POLITICALLY_EXPOSED_PERSON_REPORT",
            createdAt: "2024-11-07T13:54:08.037Z",
            activityBy: {
              source: "SALESFORCE",
              identifier: 123,
            },
            data: {
              type: "report/politically-exposed-person",
              id: "rep_AZWzzaJvf1w3TYPst1eXJ1v2BvcN",
              attributes: {
                status: "ready",
                created_at: "2024-10-22T09:56:41.000Z",
                completed_at: "2024-10-22T09:56:41.000Z",
                redacted_at: null,
                report_template_version_name: "v5",
                has_match: true,
                is_continuous: false,
                is_recurring: false,
                tags: [],
                query: {
                  name_first: "Vladimir",
                  name_middle: null,
                  name_last: "Putin",
                  term: "Vladimir Putin",
                  birthdate: "1952-10-07",
                  country_code: "RU",
                },
                result: [
                  {
                    entity_id: "Q7747",
                    name: "Vladimir Vladimirovich PUTIN",
                    aliases: [
                      "PUTIN, Vladimir Vladimirovich",
                      "Putin Vladimir Vladimirovich",
                      "Putin Volodymyr Volodymyrovych",
                      "Vladimir Poetin",
                      "Vladimir Poutine",
                      "Vladimir Putin",
                      "Vladimir Vladimirovich POUTINE",
                      "Vladimir Vladimirovich Putin",
                      "Vladimir Vladimirovitj PUTIN",
                      "Vladimir Vladimiroviç Putin",
                      "Vladimir Vladimirovič Putin",
                      "Vladimiras Putinas",
                      "Vladimirs Putins",
                      "Vladímir Putin",
                      "Vladímír Pútín",
                      "Vlagyimir Vlagyimirovics Putyin",
                      "Wladimir Poetin",
                      "Wladimir Putin",
                      "Wladimir Wladimirowitsch Putin",
                      "Władimir Putin",
                      "Βλαντίμιρ Πούτιν",
                      "Влади́мир Влади́мирович ПУ́ТИН",
                      "Владимир Владимирович Путин",
                      "Владимир Путин",
                      "Путін Володимир Володимирович",
                      "Уладзімір Уладзіміравіч Пуцін",
                      "Վլադիմիր Պուտին",
                      "ולדימיר פוטין",
                      "فلاديمير بوتين",
                      "ولادیمیر پوتین",
                      "ولادیمیر پوٹن",
                      "भ्लादिमिर पुटिन",
                      "व्लादिमीर पुतिन",
                      "ವ್ಲಾದಿಮಿರ್ ಪುತಿನ್",
                      "ဗလာဒီမီယာ ပူတင်",
                      "ვლადიმერ პუტინი",
                      "វ៉្លាឌីមៀរ ពូទីន",
                      "ウラジーミル・プーチン",
                      "弗拉基米尔·普京",
                      "블라디미르 푸틴",
                      "Vladimir PUTIN",
                      "Mr. Vladimir V. Putin",
                      "VLADIMIR VLADIMIROVICH PUTIN",
                      "Президент Путин",
                      "Путин Владимир",
                      "Путин, Владимир",
                      "Platov",
                      "Poutine",
                      "Predsjednik Putin",
                      "President Putin",
                      "Präsident Putin",
                      "Putin",
                      "Putinas",
                      "Vladimir Vladimirovici Putin",
                      "Vladimir Vladimirovitch Poutine",
                      "Vladimir Vladimirovitch Putin",
                      "Vladimir Vladimirovitj Putin",
                      "Vladimír Putin",
                      "Vladimír Vladimirovič Putin",
                      "Vladímir Vladímirovich Putin",
                      "Vladímir Vladímirovitx Putin",
                      "Wladimir Wladimirowitsj Poetin",
                      "Władimir Władimirowicz Putin",
                      "Βλαντίμιρ Βλαντίμιροβιτς Πούτιν",
                      "В. В. Путин",
                      "В.Путин",
                      "ПУ́ТИН Влади́мир Влади́мирович",
                      "Платов",
                      "Путин",
                      "Путин В. В.",
                      "Путин Владимир Владимирович",
                      "Путин, Владимир Владимирович",
                      "Путин, Владимир Владимирович,",
                      "Уладзімір Пуцін",
                      "פוטין",
                      "بوتين",
                      "فلاديمير فلاديميروفيتش بوتين",
                      "ߔߑߟߊߕߐߝ߭",
                      "ပူတင်",
                      "ウラジーミル・ウラジーミロヴィチ・プーチン",
                      "プーチン",
                      "ヴラジーミル・プーチン",
                      "ヴラジーミル・ヴラジーミロヴィチ・プーチン",
                      "ヴラジーミル・ヴラジーミロヴィッチ・プーチン",
                      "弗拉基米尔·弗拉基米罗维奇·普京",
                      "普丁",
                      "普京",
                      "블라디미르 블라디미로비치 푸틴",
                      "뿌찐",
                      "푸틴",
                      "Presiden Putin",
                    ],
                    birthdates: ["1952-10-07"],
                    death_dates: [],
                    locations: ["RU"],
                    country: null,
                    sex: "male",
                    positions: [
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President of the Russian Federation",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Premier",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Acting President of Russia",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Premier",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Supreme Commander-in-Chief of the Armed Forces of the Russian Federation",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Supreme Commander-in-Chief of the Armed Forces of the Russian Federation",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Acting President of Russia",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Premier",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Premier",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Supreme Commander-in-Chief of the Armed Forces of the Russian Federation",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "председатель Совета безопасности Российской Федерации",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President",
                      },
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "Supreme Commander-in-Chief of the Armed Forces of the Russian Federation",
                      },
                    ],
                    associates: [
                      {
                        name: "Sergei Pavlovich ROLDUGIN",
                        relationship: "Financial Manager",
                      },
                      { name: "Luiza Rozova", relationship: "Father" },
                      { name: "Luiza Rozova", relationship: "Child" },
                      {
                        name: "Alina Maratovna KABAEVA",
                        relationship: "Unmarried Partner",
                      },
                      {
                        name: "Roman Igorevich PUTIN",
                        relationship: "Relative",
                      },
                      { name: "Ludmiła Putina", relationship: "Spouse" },
                      {
                        name: "Katerina Vladimirovna TIKHONOVA",
                        relationship: "Father",
                      },
                      {
                        name: "Maria Vladimirovna VORONTSOVA",
                        relationship: "Father",
                      },
                      {
                        name: "Katerina Vladimirovna TIKHONOVA",
                        relationship: "Child",
                      },
                      {
                        name: "Maria Vladimirovna VORONTSOVA",
                        relationship: "Child",
                      },
                      {
                        name: "Igor Alexandrovich PUTIN",
                        relationship: "Relative",
                      },
                      {
                        name: "Kirill Nikolayevich SHAMALOV",
                        relationship: "Wife's Father",
                      },
                      {
                        name: "Jorrit Faassen",
                        relationship: "Wife's Father",
                      },
                      { name: "Ivan Putin", relationship: "Child" },
                      { name: "Vladimir Putin Jr.", relationship: "Child" },
                      {
                        name: "Darina Medwedtschuk",
                        relationship: "Relative",
                      },
                      { name: "Viktor Medvedchuk", relationship: "Relative" },
                      {
                        name: "Viktor Medvedchuk",
                        relationship: "Significant Person",
                      },
                    ],
                    affiliations: [],
                    related_urls: [
                      {
                        source_key: "internal-source-url",
                        name: "https://www.cia.gov/the-world-factbook/countries/russia",
                      },
                      {
                        source_key: "internal-source-url",
                        name: "https://www.cia.gov/resources/world-leaders/foreign-governments/russia",
                      },
                      {
                        source_key: "internal-source-url",
                        name: "https://www.cia.gov/resources/world-leaders/foreign-governments/russia",
                      },
                      {
                        source_key: "internal-source-url",
                        name: "https://gels-avoirs.dgtresor.gouv.fr/Gels/RegistreDetail?idRegistre=4271",
                      },
                      {
                        source_key: "internal-source-url",
                        name: "http://eng.putin.kremlin.ru/",
                      },
                      {
                        source_key: "internal-source-url",
                        name: "http://putin.kremlin.ru/",
                      },
                    ],
                    images: [
                      {
                        internal_url:
                          "https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Vladimir_Putin_in_KGB_uniform.jpg",
                        external_url:
                          "https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Vladimir_Putin_in_KGB_uniform.jpg",
                        enabled_for_similarity: true,
                        similarity_score: null,
                        similarity_level: null,
                      },
                    ],
                    sources: {
                      wikidata: {
                        url: "https://www.wikidata.org/wiki/Q7747",
                        name: "Wikidata",
                        flag_code: null,
                      },
                      dprk_reports: {
                        url: "https://dprk-reports.org/pages/about",
                        name: "DPRK Reports",
                        flag_code: "GB",
                      },
                      internal_data_source: {
                        url: "https://sanctionssearch.ofac.treas.gov/Details.aspx?id=35096",
                        name: "Internal data source",
                        flag_code: null,
                      },
                      us_cia_world_leaders: {
                        url: "https://www.cia.gov/resources/world-leaders/foreign-governments/",
                        name: "US CIA World Leaders",
                        flag_code: "US",
                      },
                      uk_fcdo_sanctions_list: {
                        url: "https://www.gov.uk/government/publications/the-uk-sanctions-list",
                        name: "UK FCDO Sanctions List",
                        flag_code: "GB",
                      },
                      acf_list_of_war_enablers: {
                        url: "https://acf.international/bribetakers-list",
                        name: "ACF List of War Enablers",
                        flag_code: "RU",
                      },
                      belgian_financial_sanctions: {
                        url: "https://finance.belgium.be/en/treasury/financial-sanctions",
                        name: "Belgian Financial Sanctions",
                        flag_code: "BE",
                      },
                      new_zealand_russia_sanctions: {
                        url: "https://www.mfat.govt.nz/en/countries-and-regions/europe/ukraine/russian-invasion-of-ukraine/sanctions/",
                        name: "New Zealand Russia Sanctions",
                        flag_code: "NZ",
                      },
                      us_sam_procurement_exclusions: {
                        url: "https://sam.gov/data-services/Exclusions/Public%20V2?privacy=Public",
                        name: "US SAM Procurement Exclusions",
                        flag_code: "US",
                      },
                      wikidata_entities_of_interest: {
                        url: "https://docs.google.com/spreadsheets/d/1UyVYpg8jF6q4zRGGlIu_SaEe_QKqfhNcEHG5KurL_r8/edit#gid=0",
                        name: "Wikidata Entities of Interest",
                        flag_code: null,
                      },
                      swiss_seco_sanctions_embargoes: {
                        url: "https://www.seco.admin.ch/seco/en/home/Aussenwirtschaftspolitik_Wirtschaftliche_Zusammenarbeit/Wirtschaftsbeziehungen/exportkontrollen-und-sanktionen/sanktionen-embargos.html",
                        name: "Swiss SECO Sanctions/Embargoes",
                        flag_code: "CH",
                      },
                      eu_financial_sanctions_files_fsf: {
                        url: "https://www.eeas.europa.eu/eeas/european-union-sanctions_en#10710",
                        name: "EU Financial Sanctions Files (FSF)",
                        flag_code: "EU",
                      },
                      lithuanian_international_sanctions: {
                        url: "https://www.fntt.lt/lt/tarptautines-finansines-sankcijos/4166",
                        name: "Lithuanian International Sanctions",
                        flag_code: "LT",
                      },
                      monaco_national_fund_freezing_list: {
                        url: "https://geldefonds.gouv.mc/",
                        name: "Monaco National Fund Freezing List",
                        flag_code: "MC",
                      },
                      wikidata_politically_exposed_persons: {
                        url: "https://www.wikidata.org/wiki/Q7747",
                        name: "Wikidata Politically Exposed Persons",
                        flag_code: null,
                      },
                      french_national_asset_freezing_system: {
                        url: "https://gels-avoirs.dgtresor.gouv.fr/",
                        name: "French National Asset Freezing System",
                        flag_code: "FR",
                      },
                      australian_sanctions_consolidated_list: {
                        url: "https://www.dfat.gov.au/international-relations/security/sanctions/Pages/sanctions",
                        name: "Australian Sanctions Consolidated List",
                        flag_code: "AU",
                      },
                      wikidata_persons_in_relevant_categories: {
                        url: "https://meta.wikimedia.org/wiki/PetScan/en",
                        name: "Wikidata Persons in Relevant Categories",
                        flag_code: null,
                      },
                      uk_hmt_ofsi_consolidated_list_of_targets: {
                        url: "https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets",
                        name: "UK HMT/OFSI Consolidated List of Targets",
                        flag_code: "GB",
                      },
                      ukraine_nsdc_state_register_of_sanctions: {
                        url: "https://drs.nsdc.gov.ua/",
                        name: "Ukraine NSDC State Register of Sanctions",
                        flag_code: "UA",
                      },
                      us_trade_consolidated_screening_list_csl: {
                        url: "https://www.trade.gov/consolidated-screening-list",
                        name: "US Trade Consolidated Screening List (CSL)",
                        flag_code: "US",
                      },
                      canadian_consolidated_autonomous_sanctions_list: {
                        url: "https://www.international.gc.ca/world-monde/international_relations-relations_internationales/sanctions/consolidated-consolide.aspx?lang=eng",
                        name: "Canadian Consolidated Autonomous Sanctions List",
                        flag_code: "CA",
                      },
                      us_ofac_specially_designated_nationals_sdn_list: {
                        url: "https://www.treasury.gov/resource-center/sanctions/Pages/default.aspx",
                        name: "US OFAC Specially Designated Nationals (SDN) List",
                        flag_code: "US",
                      },
                      us_cia_world_factbook_heads_of_state_and_government: {
                        url: "https://www.cia.gov/the-world-factbook/",
                        name: "US CIA World Factbook Heads of State and Government",
                        flag_code: "US",
                      },
                      japan_economic_sanctions_and_list_of_eligible_people: {
                        url: "https://www.mof.go.jp/policy/international_policy/gaitame_kawase/gaitame/economic_sanctions/gaiyou.html",
                        name: "Japan Economic Sanctions and List of Eligible People",
                        flag_code: "JP",
                      },
                      un_heads_of_state_heads_of_government_and_ministers_for_foreign_affairs:
                        {
                          url: "https://www.un.org/dgacm/en/content/protocol/hshgnfa",
                          name: "UN Heads of State, Heads of Government and Ministers for Foreign Affairs",
                          flag_code: null,
                        },
                    },
                    match_types: ["name_exact"],
                    pep_type: "politically_exposed_person",
                  },
                  {
                    entity_id:
                      "unprot-32bf82971599eb954c89ea33a205527cd2038596",
                    name: "Mr. Vladimir V. Putin",
                    aliases: [],
                    birthdates: [],
                    death_dates: [],
                    locations: ["RU"],
                    country: null,
                    sex: "unknown",
                    positions: [
                      {
                        pep_class: "pep-class-1",
                        source_key: "internal-data-source",
                        name: "President of the Russian Federation",
                      },
                    ],
                    associates: [],
                    affiliations: [],
                    related_urls: [],
                    images: [],
                    sources: {
                      internal_data_source: {
                        url: "",
                        name: "Internal data source",
                        flag_code: null,
                      },
                      un_heads_of_state_heads_of_government_and_ministers_for_foreign_affairs:
                        {
                          url: "https://www.un.org/dgacm/en/content/protocol/hshgnfa",
                          name: "UN Heads of State, Heads of Government and Ministers for Foreign Affairs",
                          flag_code: null,
                        },
                    },
                    match_types: ["name_exact"],
                    pep_type: "politically_exposed_person",
                  },
                ],
                run_history: [
                  {
                    scheduled_at: "2024-10-22T09:56:41.000Z",
                    completed_at: "2024-10-22T09:56:41.000Z",
                    report_template_version_id: 15000005650,
                    type: "scheduled",
                  },
                ],
                ignore_list: [],
              },
              relationships: {
                inquiry: { data: null },
                account: { data: null },
                transaction: { data: null },
                report_template: {
                  data: {
                    type: "report-template/politically-exposed-person",
                    id: "rptp_fbbNZWQyzoHcqiByfZfFtnijBhE8",
                  },
                },
              },
            },
          },
          {
            id: "e31b832a-ed48-48e0-9af4-3831070659fb",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_jcJiiSPV4xxeyPzdaaeLKM1Ag7tk",
            displayName: "POLITICALLY_EXPOSED_PERSON_REPORT",
            description: "POLITICALLY_EXPOSED_PERSON_REPORT",
            createdAt: "2024-11-07T13:54:08.037Z",
            activityBy: {
              source: "SALESFORCE",
              identifier: 123,
            },
            data: {
              type: "report/politically-exposed-person",
              id: "rep_ZAhor85Da1f1fNHx3KFBLqcPkZzn",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:54:08.000Z",
                "completed-at": "2024-11-07T13:54:09.000Z",
                "redacted-at": null,
                "report-template-version-name": "v5",
                "has-match": false,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                query: {
                  "name-first": "Praanv",
                  "name-middle": null,
                  "name-last": "Pandey",
                  term: "Praanv Pandey",
                  birthdate: "1991-10-10",
                  "country-code": "US",
                },
                result: [],
                "run-history": [
                  {
                    "scheduled-at": "2024-11-07T13:54:09.000Z",
                    "completed-at": "2024-11-07T13:54:09.000Z",
                    "report-template-version-id": 15000005650,
                    type: "scheduled",
                  },
                ],
                "ignore-list": [],
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/politically-exposed-person",
                    id: "rptp_fbbNZWQyzoHcqiByfZfFtnijBhE8",
                  },
                },
              },
            },
          },
          {
            id: "d151ac43-ca64-489b-ba19-25da35727f22",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_ZYJC9XfYcWuvG94hAju9J2Tj3ZPd",
            displayName: "POLITICALLY_EXPOSED_PERSON_REPORT",
            description: "POLITICALLY_EXPOSED_PERSON_REPORT",
            createdAt: "2024-11-07T13:53:44.218Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/politically-exposed-person",
              id: "rep_WwkjxpNZUtssfSbkynmWYEEBoUKR",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:45.000Z",
                "completed-at": "2024-11-07T13:53:45.000Z",
                "redacted-at": null,
                "report-template-version-name": "v5",
                "has-match": false,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                query: {
                  "name-first": "Praanv",
                  "name-middle": null,
                  "name-last": "Pandey",
                  term: "Praanv Pandey",
                  birthdate: "1991-10-10",
                  "country-code": "US",
                },
                result: [],
                "run-history": [
                  {
                    "scheduled-at": "2024-11-07T13:53:45.000Z",
                    "completed-at": "2024-11-07T13:53:45.000Z",
                    "report-template-version-id": 15000005650,
                    type: "scheduled",
                  },
                ],
                "ignore-list": [],
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/politically-exposed-person",
                    id: "rptp_fbbNZWQyzoHcqiByfZfFtnijBhE8",
                  },
                },
              },
            },
          },
          {
            id: "5e3d1ef9-a952-41f6-83ae-78fd620fd2b8",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_wbKR8ViBDonijuRu3it77hFRng4Z",
            displayName: "POLITICALLY_EXPOSED_PERSON_REPORT",
            description: "POLITICALLY_EXPOSED_PERSON_REPORT",
            createdAt: "2024-11-07T13:53:24.845Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/politically-exposed-person",
              id: "rep_gssUiyaBWrK8RT35eao5g99PqsRr",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:26.000Z",
                "completed-at": "2024-11-07T13:53:26.000Z",
                "redacted-at": null,
                "report-template-version-name": "v5",
                "has-match": false,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                query: {
                  "name-first": "Praanv",
                  "name-middle": null,
                  "name-last": "Pandey",
                  term: "Praanv Pandey",
                  birthdate: "1991-10-10",
                  "country-code": "US",
                },
                result: [],
                "run-history": [
                  {
                    "scheduled-at": "2024-11-07T13:53:26.000Z",
                    "completed-at": "2024-11-07T13:53:26.000Z",
                    "report-template-version-id": 15000005650,
                    type: "scheduled",
                  },
                ],
                "ignore-list": [],
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/politically-exposed-person",
                    id: "rptp_fbbNZWQyzoHcqiByfZfFtnijBhE8",
                  },
                },
              },
            },
          },
        ],
        address_lookup_report: [
          {
            id: "7da7e62c-922d-4219-9b8d-641b59f7cca7",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_YXGEtg5C6F1pDvtdQh2nGPV2MAZX",
            displayName: "ADDRESS_LOOKUP_REPORT",
            description: "ADDRESS_LOOKUP_REPORT",
            createdAt: "2024-11-07T13:54:08.556Z",
            activityBy: {
              source: "SALESFORCE",
              identifier: 123,
            },
            data: {
              type: "report/address-lookup",
              id: "rep_Zw9eBvCMFYKpoCmPYzBbmoRaQEau",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:54:09.000Z",
                "completed-at": "2024-11-07T13:54:09.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": true,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                addressee: null,
                "address-street-1": "THE WHARF DC",
                "address-street-2": "760 MAINE AVE SW",
                "address-city": "WASHINGTON",
                "address-subdivision": "DC",
                "address-postal-code": "20024",
                "resolved-addressee": null,
                "resolved-address-street-1": "600 California Street",
                "resolved-address-street-2": null,
                "resolved-address-city": "San Francisco",
                "resolved-address-subdivision": "CA",
                "resolved-address-postal-code": null,
                "metadata-record-type": "H",
                "metadata-zip-type": "Standard",
                "metadata-county-fips": "06075",
                "metadata-county-name": "San Francisco",
                "metadata-carrier-route": "C006",
                "metadata-carrier-route-type": "CityRoute",
                "metadata-congressional-district": "12",
                "metadata-building-default-indicator": "Y",
                "metadata-residential-delivery-indicator": null,
                "metadata-latitude": 37.79272,
                "metadata-longitude": -122.40443,
                "metadata-precision": "Zip9",
                "metadata-time-zone": "Pacific",
                "metadata-utc-offset": -8,
                "metadata-obeys-daylight-savings": true,
                "analysis-dpv-match-code": "D",
                "analysis-dpv-match-code-decoded":
                  "Confirmed; missing secondary info",
                "analysis-dpv-footnotes": ["AA", "N1"],
                "analysis-dpv-footnotes-decoded": [
                  "Street name, city, state, and ZIP are all valid.",
                  "Address is missing secondary information (apt, suite, unit)",
                ],
                "analysis-dpv-cmra": null,
                "analysis-dpv-vacant": null,
                "analysis-active": "Y",
                "analysis-footnotes": ["H#", "N#"],
                "analysis-footnotes-decoded": [
                  "Missing secondary number (apt, suite, etc.)",
                  "Fixed abbreviations",
                ],
                "analysis-lacs-link-code": null,
                "analysis-lacs-link-code-decoded": null,
                "analysis-lacs-link-indicator": null,
                "analysis-lacs-link-indicator-decoded": null,
                "analysis-suite-link-match": null,
                "metadata-ews-match": null,
                "error-message": null,
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/address-lookup",
                    id: "rptp_BNMsQ2a5hkozfzWvSj9nor1eQJvk",
                  },
                },
              },
            },
          },
          {
            id: "42d91534-db14-4d87-a35c-95cc5a866e35",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_CDdtPoBzUnywdyHtEqinjVJiVx6e",
            displayName: "ADDRESS_LOOKUP_REPORT",
            description: "ADDRESS_LOOKUP_REPORT",
            createdAt: "2024-11-07T13:53:44.730Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/address-lookup",
              id: "rep_tasa9sRzX7Agembcs7WiwzijDhDa",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:45.000Z",
                "completed-at": "2024-11-07T13:53:45.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": true,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                addressee: null,
                "address-street-1": "THE WHARF DC",
                "address-street-2": "760 MAINE AVE SW",
                "address-city": "WASHINGTON",
                "address-subdivision": "DC",
                "address-postal-code": "20024",
                "resolved-addressee": null,
                "resolved-address-street-1": "600 California Street",
                "resolved-address-street-2": null,
                "resolved-address-city": "San Francisco",
                "resolved-address-subdivision": "CA",
                "resolved-address-postal-code": null,
                "metadata-record-type": "H",
                "metadata-zip-type": "Standard",
                "metadata-county-fips": "06075",
                "metadata-county-name": "San Francisco",
                "metadata-carrier-route": "C006",
                "metadata-carrier-route-type": "CityRoute",
                "metadata-congressional-district": "12",
                "metadata-building-default-indicator": "Y",
                "metadata-residential-delivery-indicator": null,
                "metadata-latitude": 37.79272,
                "metadata-longitude": -122.40443,
                "metadata-precision": "Zip9",
                "metadata-time-zone": "Pacific",
                "metadata-utc-offset": -8,
                "metadata-obeys-daylight-savings": true,
                "analysis-dpv-match-code": "D",
                "analysis-dpv-match-code-decoded":
                  "Confirmed; missing secondary info",
                "analysis-dpv-footnotes": ["AA", "N1"],
                "analysis-dpv-footnotes-decoded": [
                  "Street name, city, state, and ZIP are all valid.",
                  "Address is missing secondary information (apt, suite, unit)",
                ],
                "analysis-dpv-cmra": null,
                "analysis-dpv-vacant": null,
                "analysis-active": "Y",
                "analysis-footnotes": ["H#", "N#"],
                "analysis-footnotes-decoded": [
                  "Missing secondary number (apt, suite, etc.)",
                  "Fixed abbreviations",
                ],
                "analysis-lacs-link-code": null,
                "analysis-lacs-link-code-decoded": null,
                "analysis-lacs-link-indicator": null,
                "analysis-lacs-link-indicator-decoded": null,
                "analysis-suite-link-match": null,
                "metadata-ews-match": null,
                "error-message": null,
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/address-lookup",
                    id: "rptp_BNMsQ2a5hkozfzWvSj9nor1eQJvk",
                  },
                },
              },
            },
          },
          {
            id: "a7e52eb8-9c89-412d-9dd9-5a36da34a2ce",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_RJEALA6AcrUNSdinXPc7FBVCGw4a",
            displayName: "ADDRESS_LOOKUP_REPORT",
            description: "ADDRESS_LOOKUP_REPORT",
            createdAt: "2024-11-07T13:53:25.391Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/address-lookup",
              id: "rep_YhR16ed6uKEkUkVutaefMKWG7Chc",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:26.000Z",
                "completed-at": "2024-11-07T13:53:26.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": true,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                addressee: null,
                "address-street-1": "THE WHARF DC",
                "address-street-2": "760 MAINE AVE SW",
                "address-city": "WASHINGTON",
                "address-subdivision": "DC",
                "address-postal-code": "20024",
                "resolved-addressee": null,
                "resolved-address-street-1": "600 California Street",
                "resolved-address-street-2": null,
                "resolved-address-city": "San Francisco",
                "resolved-address-subdivision": "CA",
                "resolved-address-postal-code": null,
                "metadata-record-type": "H",
                "metadata-zip-type": "Standard",
                "metadata-county-fips": "06075",
                "metadata-county-name": "San Francisco",
                "metadata-carrier-route": "C006",
                "metadata-carrier-route-type": "CityRoute",
                "metadata-congressional-district": "12",
                "metadata-building-default-indicator": "Y",
                "metadata-residential-delivery-indicator": null,
                "metadata-latitude": 37.79272,
                "metadata-longitude": -122.40443,
                "metadata-precision": "Zip9",
                "metadata-time-zone": "Pacific",
                "metadata-utc-offset": -8,
                "metadata-obeys-daylight-savings": true,
                "analysis-dpv-match-code": "D",
                "analysis-dpv-match-code-decoded":
                  "Confirmed; missing secondary info",
                "analysis-dpv-footnotes": ["AA", "N1"],
                "analysis-dpv-footnotes-decoded": [
                  "Street name, city, state, and ZIP are all valid.",
                  "Address is missing secondary information (apt, suite, unit)",
                ],
                "analysis-dpv-cmra": null,
                "analysis-dpv-vacant": null,
                "analysis-active": "Y",
                "analysis-footnotes": ["H#", "N#"],
                "analysis-footnotes-decoded": [
                  "Missing secondary number (apt, suite, etc.)",
                  "Fixed abbreviations",
                ],
                "analysis-lacs-link-code": null,
                "analysis-lacs-link-code-decoded": null,
                "analysis-lacs-link-indicator": null,
                "analysis-lacs-link-indicator-decoded": null,
                "analysis-suite-link-match": null,
                "metadata-ews-match": null,
                "error-message": null,
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/address-lookup",
                    id: "rptp_BNMsQ2a5hkozfzWvSj9nor1eQJvk",
                  },
                },
              },
            },
          },
        ],
        email_risk_report: [
          {
            id: "a7fe30ad-2f4b-4d01-9f98-00b9bb223134",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_fiBkQ5oAuqRyjLMXyK58GePvAU12",
            displayName: "EMAIL_RISK_REPORT",
            description: "EMAIL_RISK_REPORT",
            createdAt: "2024-11-07T13:54:09.011Z",
            activityBy: {
              source: "SALESFORCE",
              identifier: 123,
            },
            data: {
              type: "report/email-address",
              id: "rep_hmhZWnfAQD1qSaLUPGDwBpZ19a19",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:54:10.000Z",
                "completed-at": "2024-11-07T13:54:10.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": true,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                "email-address": "pranav@gmail.com",
                "email-reputation": "high",
                "email-reference-count": null,
                "email-domain-reputation": null,
                "email-first-seen-days": null,
                "email-estimated-age-days": 663,
                "email-last-seen-days": null,
                "email-domain-age-days": 2236,
                "email-credentials-leaked": null,
                "email-credentials-leaked-recent": false,
                "email-data-breached": null,
                "email-malicious-activity-detected": null,
                "email-malicious-activity-detected-recent": false,
                "email-is-blocklisted": null,
                "email-is-spam": false,
                "email-is-free-provider": null,
                "email-is-disposable": false,
                "email-is-deliverable": true,
                "email-is-valid-mx": true,
                "email-is-spoofable": null,
                "email-is-spf-strict": null,
                "email-is-dmarc-enforced": null,
                "email-is-suspicious": false,
                "email-domain-exists": true,
                "email-domain": "gmail.com",
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/email-address",
                    id: "rptp_fw94TejHmAbrQRpPdrceS4kFTExR",
                  },
                },
              },
            },
          },
          {
            id: "101a2fbe-0b6a-4317-8edf-78ae688bf6c0",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_zXUunB4AX9wB8b6YUVBYF6QHAjjf",
            displayName: "EMAIL_RISK_REPORT",
            description: "EMAIL_RISK_REPORT",
            createdAt: "2024-11-07T13:53:45.259Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/email-address",
              id: "rep_hnUrAD638AkDqYHWjSMpQhyrKmTN",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:46.000Z",
                "completed-at": "2024-11-07T13:53:46.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": true,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                "email-address": "pranav@gmail.com",
                "email-reputation": "high",
                "email-reference-count": null,
                "email-domain-reputation": null,
                "email-first-seen-days": null,
                "email-estimated-age-days": 663,
                "email-last-seen-days": null,
                "email-domain-age-days": 2236,
                "email-credentials-leaked": null,
                "email-credentials-leaked-recent": false,
                "email-data-breached": null,
                "email-malicious-activity-detected": null,
                "email-malicious-activity-detected-recent": false,
                "email-is-blocklisted": null,
                "email-is-spam": false,
                "email-is-free-provider": null,
                "email-is-disposable": false,
                "email-is-deliverable": true,
                "email-is-valid-mx": true,
                "email-is-spoofable": null,
                "email-is-spf-strict": null,
                "email-is-dmarc-enforced": null,
                "email-is-suspicious": false,
                "email-domain-exists": true,
                "email-domain": "gmail.com",
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/email-address",
                    id: "rptp_fw94TejHmAbrQRpPdrceS4kFTExR",
                  },
                },
              },
            },
          },
          {
            id: "cae4bba3-9ab2-48b0-9822-394b12e39e4a",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_pzk2fbjhv6DivBooQE6Jd6bmFKFU",
            displayName: "EMAIL_RISK_REPORT",
            description: "EMAIL_RISK_REPORT",
            createdAt: "2024-11-07T13:53:26.074Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/email-address",
              id: "rep_61CV9YHSjThprPWGVY3S9jvPNX1U",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:26.000Z",
                "completed-at": "2024-11-07T13:53:26.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": true,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                "email-address": "pranav@gmail.com",
                "email-reputation": "high",
                "email-reference-count": null,
                "email-domain-reputation": null,
                "email-first-seen-days": null,
                "email-estimated-age-days": 663,
                "email-last-seen-days": null,
                "email-domain-age-days": 2236,
                "email-credentials-leaked": null,
                "email-credentials-leaked-recent": false,
                "email-data-breached": null,
                "email-malicious-activity-detected": null,
                "email-malicious-activity-detected-recent": false,
                "email-is-blocklisted": null,
                "email-is-spam": false,
                "email-is-free-provider": null,
                "email-is-disposable": false,
                "email-is-deliverable": true,
                "email-is-valid-mx": true,
                "email-is-spoofable": null,
                "email-is-spf-strict": null,
                "email-is-dmarc-enforced": null,
                "email-is-suspicious": false,
                "email-domain-exists": true,
                "email-domain": "gmail.com",
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/email-address",
                    id: "rptp_fw94TejHmAbrQRpPdrceS4kFTExR",
                  },
                },
              },
            },
          },
        ],
        phone_risk_report: [
          {
            id: "b95d5c5c-8330-4d70-bea5-00c252f095dd",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_M3qV5xsW3whE2cGeyk41ChQXREN1",
            displayName: "PHONE_RISK_REPORT",
            description: "PHONE_RISK_REPORT",
            createdAt: "2024-11-07T13:54:09.682Z",
            activityBy: {
              source: "SALESFORCE",
              identifier: 123,
            },
            data: {
              type: "report/phone-number",
              id: "rep_zauzfVFpBABZXHrLFJMGxKzGoq2u",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:54:11.000Z",
                "completed-at": "2024-11-07T13:54:11.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": false,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                "phone-number": "9008369803",
                "phone-type": "MOBILE",
                "phone-carrier": "Sandbox Phone Carrier",
                "phone-risk-level": "medium-low",
                "phone-risk-recommendation": "allow",
                "phone-risk-score": 250,
                "phone-risk-sim-swap": null,
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/phone-number",
                    id: "rptp_vG3S24iKLkeC5jDFb1CNB3L1Gmr9",
                  },
                },
              },
            },
          },
          {
            id: "76e43395-d761-4330-b2b8-eaea91f946d9",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_PeKoEJ5VaDrRnV18YhQw2ngW2CAs",
            displayName: "PHONE_RISK_REPORT",
            description: "PHONE_RISK_REPORT",
            createdAt: "2024-11-07T13:53:45.804Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/phone-number",
              id: "rep_LxQnrjmUZTmftKucmqsYMFmUjzEa",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:46.000Z",
                "completed-at": "2024-11-07T13:53:46.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": false,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                "phone-number": "9008369803",
                "phone-type": "MOBILE",
                "phone-carrier": "Sandbox Phone Carrier",
                "phone-risk-level": "medium-low",
                "phone-risk-recommendation": "allow",
                "phone-risk-score": 250,
                "phone-risk-sim-swap": null,
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/phone-number",
                    id: "rptp_vG3S24iKLkeC5jDFb1CNB3L1Gmr9",
                  },
                },
              },
            },
          },
          {
            id: "2f8dc7dd-6466-4d5c-8c56-ec86e722e966",
            status: "READY",
            statusColor: "GREEN",
            externalVerificationId: "persona:txn_3EQ7NsNFeXghTGefM6waK4nqG6z8",
            displayName: "PHONE_RISK_REPORT",
            description: "PHONE_RISK_REPORT",
            createdAt: "2024-11-07T13:53:26.588Z",
            activityBy: {
              source: "HARMONEY",
              identifier: 123,
            },
            data: {
              type: "report/phone-number",
              id: "rep_sULT3sRZBZp4CPkwmfovC1tZyBvJ",
              attributes: {
                status: "ready",
                "created-at": "2024-11-07T13:53:27.000Z",
                "completed-at": "2024-11-07T13:53:27.000Z",
                "redacted-at": null,
                "report-template-version-name": "v1",
                "has-match": false,
                "is-continuous": false,
                "is-recurring": false,
                tags: [],
                "phone-number": "9008369803",
                "phone-type": "MOBILE",
                "phone-carrier": "Sandbox Phone Carrier",
                "phone-risk-level": "medium-low",
                "phone-risk-recommendation": "allow",
                "phone-risk-score": 250,
                "phone-risk-sim-swap": null,
              },
              relationships: {
                inquiry: {
                  data: null,
                },
                account: {
                  data: null,
                },
                transaction: {
                  data: null,
                },
                "report-template": {
                  data: {
                    type: "report-template/phone-number",
                    id: "rptp_vG3S24iKLkeC5jDFb1CNB3L1Gmr9",
                  },
                },
              },
            },
          },
        ],
        government_id_verification: [
          {
            id: "87d0085e-e188-4229-9a8b-2d6af89b19f6",
            status: "PASSED",
            statusColor: "GREEN",
            externalVerificationId: "persona:inq_3tTLsn1JjTwfhSKRcv2dqcSARAkR",
            displayName: "Government Id verification",
            description: "Government Id verification",
            createdAt: "2024-11-07T11:33:51.701Z",
            activityBy: {
              source: "NAO_WEB",
              identifier: "5tH5YUUSNqpPqrAzXci1",
            },
            data: {
              type: "verification/government-id",
              id: "ver_Ecn1SZBA64KceUsfkpDL8UXLsyVR",
              attributes: {
                status: "passed",
                "created-at": "2024-11-07T11:34:10.000Z",
                "created-at-ts": 1730979250,
                "submitted-at": "2024-11-07T11:34:11.000Z",
                "submitted-at-ts": 1730979251,
                "completed-at": "2024-11-07T11:34:12.000Z",
                "completed-at-ts": 1730979252,
                "country-code": "US",
                "entity-confidence-score": 100,
                "entity-confidence-reasons": ["generic"],
                "front-photo-url":
                  "https://files.withpersona.com/image+%285%29.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemUzbGFrMm5ucnpqcHByY2N2OW5tdzgxZjhlIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjIyNmFhYzc0LTdhY2UtNDgwMy1iZTk2LTU4Nzk4NDUzNDhiNSIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoicHJvY2Vzc2VkIiwiZXhwIjoxNzMxMDA5NDM2fQ.kDFeDkvBz2Hq5LeIfMMd_OclrJ2_JWavvZqFdj77FM4",
                "back-photo-url":
                  "https://files.withpersona.com/image+%285%29.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1M3pqdXllN2ZjdjBpZ2NpdHo0aDAwdmUxeGNhIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjA1Y2RkMTQ3LWJjNmEtNGEzYS1hNjE4LTI0M2ZjY2Q2ODQ1OCIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoicHJvY2Vzc2VkIiwiZXhwIjoxNzMxMDA5NDM2fQ.fvtS4BLi2K7_lHLwzOtFYI5vE6uFwsvq3xoKSvMTPAE",
                "photo-urls": [
                  {
                    page: "front",
                    url: "https://files.withpersona.com/image+%285%29.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemUzbGFrMm5ucnpqcHByY2N2OW5tdzgxZjhlIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjhhYTcwOTM2LWJkOWMtNGU5ZC05YWYxLWU3NjFhZjAxNDcxNiIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoicHJvY2Vzc2VkIiwiZXhwIjoxNzMxMDA5NDM2fQ.36EoxsVX0d53KLHpb7rZi-eoG6nakD6bqGpFxBSp1p8",
                    "normalized-url":
                      "https://files.withpersona.com/image+%285%29.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5dmthZWtsMzZzcDZ4bDFxbXJ2aHI1anFoMzgzIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjEzMzc3MjcyLTQzM2YtNDZjMC04ZWQyLWY0OThlNDZiODY5MSIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoibm9ybWFsaXplZCIsImV4cCI6MTczMTAwOTQzNn0.qWrbiGlMAEfyssRSWkUdBl45yXJsGO55H6qcH6VoGGg",
                    "original-urls": [
                      "https://files.withpersona.com/image+%285%29.png?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2NmI0aG1iY3VkNWowNWs0c3J0azJ6enAxY21iIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjlmZDUyMDg5LWFlYzktNDhlYS1iNGUwLWNjMGUxNWZkNDczYiIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoib3JpZ2luYWxzIiwiZXhwIjoxNzMxMDA5NDM2fQ.hKATRjNXBiC6PKC82hR2bnpq5D61Mw-4DGmniTRmUYE",
                    ],
                    "byte-size": 320850,
                  },
                  {
                    page: "back",
                    url: "https://files.withpersona.com/image+%285%29.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1M3pqdXllN2ZjdjBpZ2NpdHo0aDAwdmUxeGNhIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6ImFiYTViMmQyLWUwM2MtNDY5ZS1iMWVkLTBkZTg1YWE1MTg4MiIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoicHJvY2Vzc2VkIiwiZXhwIjoxNzMxMDA5NDM2fQ.uXOo7qoCyjeEuOB2Xh2v75Tfyng-xaPrSiNXFmp5Ws4",
                    "normalized-url":
                      "https://files.withpersona.com/image+%285%29.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaHVmaHNzemlkaW4xamRzZnN0eGt2czJhcjBtIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjUxODZkMDc3LWZlYjYtNGUzOS1iNmU5LTBjYjlkNzRmOWZiMiIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoibm9ybWFsaXplZCIsImV4cCI6MTczMTAwOTQzNn0.1RQsdFTsV4P7et2JF3iDW13hGc5qxDTZmXaCzgNSaGo",
                    "original-urls": [
                      "https://files.withpersona.com/image+%285%29.png?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhNDhpZ3NjaHlmNHhhdGR5dTZuZ2pnOXF4bnczIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6ImI1ZmQ0OWQ1LTg2MTAtNGM0MS1hYzFiLTVkY2NkZWEzY2FjOCIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoib3JpZ2luYWxzIiwiZXhwIjoxNzMxMDA5NDM2fQ.-YsrNWmnZD3LXy0OtLb04bS46pb-gO_2ll9QWmA8W-o",
                    ],
                    "byte-size": 320850,
                  },
                ],
                "selfie-photo": {
                  url: "https://files.withpersona.com/selfie_photo.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxOXpqY3hrZjgybHNtdzFybGZxcmE5MG1xaGRhIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjcxYmI2NWNmLTBjYjEtNDhhMy05ZGVlLTI3ZGUwMmJiZmJkYSIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoic2VsZmllX3Bob3RvIiwiZXhwIjoxNzMxMDA5NDM2fQ.6s-AFQV-4_78clBfkkK4GOsxwhppIbJNK8Zo6RTJrLc",
                  "byte-size": 320850,
                },
                "selfie-photo-url":
                  "https://files.withpersona.com/selfie_photo.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxOXpqY3hrZjgybHNtdzFybGZxcmE5MG1xaGRhIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM2LCJuYmYiOjE3MzA5ODc4MzYsImp0aSI6IjAwZjFiOTdhLWUwYjYtNDUwZS1iZDBkLTE3MzZjN2M3ZTRjMCIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJnb3Zlcm5tZW50X2lkX2ZpbGVzIiwiZmlsZV9pbmZvIjoic2VsZmllX3Bob3RvIiwiZXhwIjoxNzMxMDA5NDM2fQ.0HzumgfV4-5R6rUwNHa8G1VJjnXEXr9sn3JUF1zlLqg",
                "video-url": null,
                "id-class": "dl",
                "capture-method": "upload",
                "name-first": "ALEXANDER J",
                "name-middle": null,
                "name-last": "SAMPLE",
                "name-suffix": null,
                birthdate: "1977-07-17",
                "address-street-1": "600 CALIFORNIA STREET",
                "address-street-2": null,
                "address-city": "SAN FRANCISCO",
                "address-subdivision": "CA",
                "address-postal-code": "94109",
                "issuing-authority": "CA",
                "issuing-subdivision": "CA",
                nationality: null,
                "document-number": null,
                "visa-status": null,
                "issue-date": "2023-11-07",
                "expiration-date": "2029-11-07",
                designations: null,
                birthplace: null,
                endorsements: null,
                height: null,
                sex: "Male",
                restrictions: null,
                "vehicle-class": null,
                "identification-number": "I1234562",
                checks: [
                  {
                    name: "id_aamva_database_lookup",
                    status: "not_applicable",
                    reasons: ["disabled_by_check_config"],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_account_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_age_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_age_inconsistency_detection",
                    status: "not_applicable",
                    reasons: ["disabled_by_check_config"],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_attribute_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_barcode_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_barcode_inconsistency_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_blur_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_color_inconsistency_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_compromised_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_disallowed_country_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {
                      "country-code": null,
                      "selected-country-code": null,
                    },
                  },
                  {
                    name: "id_disallowed_type_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {
                      "country-code": null,
                      "detected-id-class": null,
                      "detected-id-designations": null,
                      "disallowed-id-designations": null,
                      "selected-id-classes": null,
                    },
                  },
                  {
                    name: "id_double_side_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_electronic_replica_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_entity_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_experimental_model_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_expired_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_extracted_properties_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_extraction_inconsistency_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {
                      "check-requirements": [],
                    },
                  },
                  {
                    name: "id_fabrication_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_glare_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_handwriting_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_inconsistent_repeat_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_inquiry_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_mrz_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_mrz_inconsistency_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_number_format_inconsistency_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_paper_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_po_box_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_portrait_clarity_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_portrait_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_public_figure_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_real_id_detection",
                    status: "not_applicable",
                    reasons: ["disabled_by_check_config"],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_repeat_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_selfie_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_tamper_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "id_unprocessable_submission_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_valid_dates_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "id_video_quality_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                ],
              },
              relationships: {
                inquiry: {
                  data: {
                    type: "inquiry",
                    id: "inq_3tTLsn1JjTwfhSKRcv2dqcSARAkR",
                  },
                },
                template: {
                  data: null,
                },
                "inquiry-template-version": {
                  data: {
                    type: "inquiry-template-version",
                    id: "itmplv_8yp4LnhQdRWSJC23uzjfyG51xXub",
                  },
                },
                "inquiry-template": {
                  data: {
                    type: "inquiry-template",
                    id: "itmpl_oDcSP2qVFy2TjUY9D9yH2aXh",
                  },
                },
                "verification-template": {
                  data: {
                    type: "verification-template/government-id",
                    id: "vtmpl_PUN3374NFjRYJ8zRLrkHCNg3",
                  },
                },
                "verification-template-version": {
                  data: {
                    type: "verification-template-version/government-id",
                    id: "vtmplv_5iT2Krpi3XCeZcKifC13V8iFNKEZ",
                  },
                },
                transaction: {
                  data: null,
                },
                document: {
                  data: {
                    type: "document/government-id",
                    id: "doc_aqmLVyY8cYnsyyKWPy6rpW5iVftx",
                  },
                },
              },
            },
          },
        ],
        selfie_verification: [
          {
            id: "73e3e797-7e2c-4338-a3a1-767e63226d21",
            status: "PASSED",
            statusColor: "GREEN",
            externalVerificationId: "persona:inq_3tTLsn1JjTwfhSKRcv2dqcSARAkR",
            displayName: "Selfie verification",
            description: "Selfie verification",
            createdAt: "2024-11-07T11:33:51.719Z",
            activityBy: {
              source: "NAO_WEB",
              identifier: "5tH5YUUSNqpPqrAzXci1",
            },
            data: {
              type: "verification/selfie",
              id: "ver_354yUoofbKdLrS8KYAcDs4vdyfhd",
              attributes: {
                status: "passed",
                "created-at": "2024-11-07T11:34:27.000Z",
                "created-at-ts": 1730979267,
                "submitted-at": "2024-11-07T11:34:27.000Z",
                "submitted-at-ts": 1730979267,
                "completed-at": "2024-11-07T11:34:28.000Z",
                "completed-at-ts": 1730979268,
                "country-code": null,
                "left-photo-url":
                  "https://files.withpersona.com/selfiefile%2Fimage%2F15089256004%2Fshrine_processed%2F740cebbf91b05dacd6e8446ed6a59b9c.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWxmaWVmaWxlL2ltYWdlLzE1MDg5MjU2MDA0L3NocmluZV9wcm9jZXNzZWQvNzQwY2ViYmY5MWIwNWRhY2Q2ZTg0NDZlZDZhNTliOWMuanBnIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM1LCJuYmYiOjE3MzA5ODc4MzUsImp0aSI6IjNlZDZiMDQ2LTA1YjUtNGU4MC1hNDg2LWE4MWY1OTg1YTBlYyIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJTaHJpbmU6OlVwbG9hZGVkRmlsZSIsImZpbGVfaW5mbyI6InNlbGZpZWZpbGUvaW1hZ2UvMTUwODkyNTYwMDQvc2hyaW5lX3Byb2Nlc3NlZC83NDBjZWJiZjkxYjA1ZGFjZDZlODQ0NmVkNmE1OWI5Yy5qcGciLCJleHAiOjE3MzEwMDk0MzV9.ktLt0cXYQC6gamAEiu0tv5o0n3MtUjV7_LgV_Fs6TWw",
                "center-photo-url":
                  "https://files.withpersona.com/selfiefile%2Fimage%2F15089256003%2Fshrine_processed%2F4054467b2b3bd0533346c7d876094acf.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWxmaWVmaWxlL2ltYWdlLzE1MDg5MjU2MDAzL3NocmluZV9wcm9jZXNzZWQvNDA1NDQ2N2IyYjNiZDA1MzMzNDZjN2Q4NzYwOTRhY2YuanBnIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM1LCJuYmYiOjE3MzA5ODc4MzUsImp0aSI6IjUzOTQyYTMxLTVlNzUtNDQ3OC1iOTA4LTU5OTA5MDljYjQ1NCIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJTaHJpbmU6OlVwbG9hZGVkRmlsZSIsImZpbGVfaW5mbyI6InNlbGZpZWZpbGUvaW1hZ2UvMTUwODkyNTYwMDMvc2hyaW5lX3Byb2Nlc3NlZC80MDU0NDY3YjJiM2JkMDUzMzM0NmM3ZDg3NjA5NGFjZi5qcGciLCJleHAiOjE3MzEwMDk0MzV9.rj-uUSLIErggIEyRanAjOJb5Yt0y6nESe4BzwAHYwwY",
                "right-photo-url":
                  "https://files.withpersona.com/selfiefile%2Fimage%2F15089256005%2Fshrine_processed%2F43b75e4f839fd954497828bcb06a5218.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWxmaWVmaWxlL2ltYWdlLzE1MDg5MjU2MDA1L3NocmluZV9wcm9jZXNzZWQvNDNiNzVlNGY4MzlmZDk1NDQ5NzgyOGJjYjA2YTUyMTguanBnIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM1LCJuYmYiOjE3MzA5ODc4MzUsImp0aSI6ImUyYmI3MjNmLTNhMDgtNGU5My1iYzhiLTFmM2FjZTMzNDlkYSIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJTaHJpbmU6OlVwbG9hZGVkRmlsZSIsImZpbGVfaW5mbyI6InNlbGZpZWZpbGUvaW1hZ2UvMTUwODkyNTYwMDUvc2hyaW5lX3Byb2Nlc3NlZC80M2I3NWU0ZjgzOWZkOTU0NDk3ODI4YmNiMDZhNTIxOC5qcGciLCJleHAiOjE3MzEwMDk0MzV9.Fpojj0qGO5TxahNXIkm7M6MgDvKGHlP7Srl9a51uQgc",
                "photo-urls": [
                  {
                    page: "left_photo",
                    url: "https://files.withpersona.com/selfiefile%2Fimage%2F15089256004%2Fshrine_processed%2F740cebbf91b05dacd6e8446ed6a59b9c.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWxmaWVmaWxlL2ltYWdlLzE1MDg5MjU2MDA0L3NocmluZV9wcm9jZXNzZWQvNzQwY2ViYmY5MWIwNWRhY2Q2ZTg0NDZlZDZhNTliOWMuanBnIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM1LCJuYmYiOjE3MzA5ODc4MzUsImp0aSI6IjQzMmNmMWI1LTZmZjEtNGNmNC1iZGY0LTNmZGNmZTcxMTFkMCIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJTaHJpbmU6OlVwbG9hZGVkRmlsZSIsImZpbGVfaW5mbyI6InNlbGZpZWZpbGUvaW1hZ2UvMTUwODkyNTYwMDQvc2hyaW5lX3Byb2Nlc3NlZC83NDBjZWJiZjkxYjA1ZGFjZDZlODQ0NmVkNmE1OWI5Yy5qcGciLCJleHAiOjE3MzEwMDk0MzV9.S6lLFSnk9N0XTzER5WJ2PSwLD1XlHdph-OD-kttKKNk",
                    "byte-size": 195062,
                  },
                  {
                    page: "center_photo",
                    url: "https://files.withpersona.com/selfiefile%2Fimage%2F15089256003%2Fshrine_processed%2F4054467b2b3bd0533346c7d876094acf.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWxmaWVmaWxlL2ltYWdlLzE1MDg5MjU2MDAzL3NocmluZV9wcm9jZXNzZWQvNDA1NDQ2N2IyYjNiZDA1MzMzNDZjN2Q4NzYwOTRhY2YuanBnIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM1LCJuYmYiOjE3MzA5ODc4MzUsImp0aSI6IjM3ODRhN2FhLWQ2MGYtNDAxZi05NTMyLWM5YTE3YTEwNzUxYyIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJTaHJpbmU6OlVwbG9hZGVkRmlsZSIsImZpbGVfaW5mbyI6InNlbGZpZWZpbGUvaW1hZ2UvMTUwODkyNTYwMDMvc2hyaW5lX3Byb2Nlc3NlZC80MDU0NDY3YjJiM2JkMDUzMzM0NmM3ZDg3NjA5NGFjZi5qcGciLCJleHAiOjE3MzEwMDk0MzV9.znM0GZXO7SU4mLY_mv8XLZ3HQrZTPuSHG5HgVt7D4As",
                    "byte-size": 189770,
                  },
                  {
                    page: "right_photo",
                    url: "https://files.withpersona.com/selfiefile%2Fimage%2F15089256005%2Fshrine_processed%2F43b75e4f839fd954497828bcb06a5218.jpg?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZWxmaWVmaWxlL2ltYWdlLzE1MDg5MjU2MDA1L3NocmluZV9wcm9jZXNzZWQvNDNiNzVlNGY4MzlmZDk1NDQ5NzgyOGJjYjA2YTUyMTguanBnIiwiYXVkIjoiZmlsZXMud2l0aHBlcnNvbmEuY29tIiwiaXNzIjoid2l0aHBlcnNvbmEuY29tIiwiaWF0IjoxNzMwOTg3ODM1LCJuYmYiOjE3MzA5ODc4MzUsImp0aSI6IjZlMDY2MWU3LTMyMTAtNDExMS04ZWU4LTA0YTllNzEyNDJjMiIsImdjc19idWNrZXQiOiJwZXJzb25hLXdlYiIsImZpbGVfZW5jcnlwdGVkIjp0cnVlLCJmaWxlX3NhbHQiOiJTaHJpbmU6OlVwbG9hZGVkRmlsZSIsImZpbGVfaW5mbyI6InNlbGZpZWZpbGUvaW1hZ2UvMTUwODkyNTYwMDUvc2hyaW5lX3Byb2Nlc3NlZC80M2I3NWU0ZjgzOWZkOTU0NDk3ODI4YmNiMDZhNTIxOC5qcGciLCJleHAiOjE3MzEwMDk0MzV9.FgFxcu6qmzsnUGb2W6tIzBps7Wm3-L_N2zhxEzXUrL4",
                    "byte-size": 197253,
                  },
                ],
                "video-url": null,
                "center-photo-face-coordinates": null,
                "entity-confidence-reasons": [],
                "document-similarity-score": null,
                "selfie-similarity-score-left": null,
                "selfie-similarity-score-right": null,
                checks: [
                  {
                    name: "selfie_attribute_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "selfie_id_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_pose_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_multiple_faces_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_pose_repeat_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_account_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_suspicious_entity_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_liveness_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_glasses_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "selfie_glare_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "selfie_experimental_model_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "selfie_portrait_quality_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "selfie_public_figure_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "selfie_age_comparison",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                  {
                    name: "selfie_face_covering_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "required",
                    metadata: {},
                  },
                  {
                    name: "selfie_video_quality_detection",
                    status: "passed",
                    reasons: [],
                    requirement: "not_required",
                    metadata: {},
                  },
                ],
                "capture-method": "video",
              },
              relationships: {
                inquiry: {
                  data: {
                    type: "inquiry",
                    id: "inq_3tTLsn1JjTwfhSKRcv2dqcSARAkR",
                  },
                },
                template: {
                  data: null,
                },
                "inquiry-template-version": {
                  data: {
                    type: "inquiry-template-version",
                    id: "itmplv_8yp4LnhQdRWSJC23uzjfyG51xXub",
                  },
                },
                "inquiry-template": {
                  data: {
                    type: "inquiry-template",
                    id: "itmpl_oDcSP2qVFy2TjUY9D9yH2aXh",
                  },
                },
                "verification-template": {
                  data: {
                    type: "verification-template/selfie",
                    id: "vtmpl_poZqBZ3fqGWswXXgMjexcFGo",
                  },
                },
                "verification-template-version": {
                  data: {
                    type: "verification-template-version/selfie",
                    id: "vtmplv_Rqn6urdxs1kPx57pMiwWnJDf8PMZ",
                  },
                },
                transaction: {
                  data: null,
                },
              },
            },
          },
        ],
      },
    },
  ],
};
